<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Wpf_resource_Pack_Uri_Binary</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resource\Images\riv.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resource\Images\riv.jpg" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resource\Images\doraemon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
